name: gif
description: Control a gif using flutter animation controller. You can either specify a fixed duration or set the framerate of the playback.
version: 2.3.0
homepage: https://github.com/pierluigizagaria/flutter_gif

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
